"""
Interactive manual fitting tool for compliant muscle parameters.

Usage:
    python manual_fit_gui.py --muscle glmax1_r \
        --data_dir osim_muscle_data \
        --params_csv osim_muscle_data/all_muscle_parameters.csv

Notes:
- Uses the v=0 length-force data (total force) generated by extract_muscle_force_sim.py.
- Sliders adjust the 9 MuJoCo compliant tendon parameters.
- The plot updates live; press "Print params" to log current values to stdout.
"""

import argparse
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider, Button

from myoleg_muscle_param import (
    CompliantTendonParams,
    create_model,
    compute_forces_at_velocity,
    load_length_force_sim,
)


def build_sliders(ax_start, slider_height, slider_space, names, init_vals, mins, maxs):
    sliders = []
    current_ax_y = ax_start
    for name, init, vmin, vmax in zip(names, init_vals, mins, maxs):
        # Guard against zero range; expand slightly if needed
        if vmax <= vmin:
            vmax = vmin + 1e-6
        step = (vmax - vmin) / 200.0 if vmax > vmin else None
        # Clip initial value into bounds
        init_clipped = min(max(init, vmin), vmax)
        ax = plt.axes([0.15, current_ax_y, 0.7, slider_height])
        slider = Slider(ax, name, vmin, vmax, valinit=init_clipped, valstep=step)
        sliders.append(slider)
        current_ax_y -= slider_height + slider_space
    return sliders


def main():
    parser = argparse.ArgumentParser(description="Manual MuJoCo muscle parameter fitting GUI")
    parser.add_argument("--muscle", required=True, help="Muscle name (e.g., glmax1_r)")
    parser.add_argument("--data_dir", default="osim_muscle_data", help="Directory with *_sim_total.csv")
    parser.add_argument("--params_csv", default="osim_muscle_data/all_muscle_parameters.csv", help="CSV with base params")
    args = parser.parse_args()

    target = load_length_force_sim(args.muscle, args.params_csv, args.data_dir)
    mtu_lengths = target["mtu_lengths"]
    f_data = target["force_matrix"][:, 0]  # v=0 total force

    # Initial guess from CSV
    base_F = target["f_max"]
    base_L_opt = target["l_opt"]
    base_L_slack = target["l_slack"]
    base_V_max = target["v_max"]
    init_params = [
        base_F,
        base_L_opt,
        base_L_slack,
        base_V_max,
        0.56,
        -2.995732274,
        1.5,
        5.0,
        0.04,
    ]

    # Bounds for sliders (wider for manual exploration)
    mins = [
        base_F * 0.2,
        base_L_opt * 0.5,
        base_L_slack * 0.5,
        base_V_max,
        0.05,
        -10.0,
        0.5,
        2.0,
        0.01,
    ]
    maxs = [
        base_F * 2.0,
        base_L_opt * 1.8,
        base_L_slack * 1.8,
        base_V_max,
        1.5,
        -0.1,
        3.0,
        10.0,
        0.6,
    ]

    fig, ax = plt.subplots(figsize=(7, 5))
    plt.subplots_adjust(bottom=0.45)

    dense_L = np.linspace(mtu_lengths.min(), mtu_lengths.max(), 40)
    line_data, = ax.plot(mtu_lengths, f_data, "k.", label="data v=0")
    line_fit, = ax.plot(dense_L, np.zeros_like(dense_L), "r-", label="fit v=0")
    ax.set_title(f"{args.muscle} manual fit (v=0)")
    ax.set_xlabel("MTU length (m)")
    ax.set_ylabel("Force (N)")
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize="small")

    slider_names = ["F_max", "l_opt", "l_slack", "v_max", "W", "C", "N", "K", "E_REF"]
    sliders = build_sliders(
        ax_start=0.40,
        slider_height=0.03,
        slider_space=0.005,
        names=slider_names,
        init_vals=init_params,
        mins=mins,
        maxs=maxs,
    )

    # Buttons
    ax_print = plt.axes([0.85, 0.04, 0.1, 0.04])
    btn_print = Button(ax_print, "Print params")

    def current_params():
        vals = [s.val for s in sliders]
        return CompliantTendonParams(
            F_max=vals[0],
            l_opt=vals[1],
            l_slack=vals[2],
            v_max=vals[3],
            W=vals[4],
            C=vals[5],
            N=vals[6],
            K=vals[7],
            E_REF=vals[8],
        )

    def update_plot(_=None):
        params = current_params()
        model = create_model(params)
        data = None
        data = model.makeData() if hasattr(model, "makeData") else None  # type: ignore
        if data is None:
            import mujoco
            data = mujoco.MjData(model)
        f_sim = compute_forces_at_velocity(model, data, 0.0, dense_L, activation=1.0)
        line_fit.set_ydata(f_sim)
        ax.relim()
        ax.autoscale_view()
        fig.canvas.draw_idle()

    def on_print(_event):
        vals = [s.val for s in sliders]
        print(
            f"Params: F={vals[0]:.4f}, l_opt={vals[1]:.4f}, l_slack={vals[2]:.4f}, v_max={vals[3]:.4f}, "
            f"W={vals[4]:.4f}, C={vals[5]:.4f}, N={vals[6]:.4f}, K={vals[7]:.4f}, E_REF={vals[8]:.4f}"
        )

    for s in sliders:
        s.on_changed(update_plot)
    btn_print.on_clicked(on_print)

    update_plot()
    plt.show()


if __name__ == "__main__":
    main()

